package com.example.model

object SampleData {

  val promoBanners = listOf(
    PromoBanner(
      id = "promo_1",
      title = "Next-Gen Tech Expo 2026",
      subtitle = "Up to 45% OFF Quantum Audio & Smart Wearables",
      tag = "EXCLUSIVE LAUNCH",
      discountLabel = "45% OFF",
      imageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&auto=format&fit=crop&q=80",
      promoCode = "POSTATECH"
    ),
    PromoBanner(
      id = "promo_2",
      title = "Neon Runway Summer Drop",
      subtitle = "Curated Urban Streetwear & High-Top Kicks",
      tag = "TRENDING NOW",
      discountLabel = "30% OFF",
      imageUrl = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200&auto=format&fit=crop&q=80",
      promoCode = "POSTA2026"
    ),
    PromoBanner(
      id = "promo_3",
      title = "Midnight Super Flash Sale",
      subtitle = "Limited Drops, Priority Express Shipping",
      tag = "FLASH SALE",
      discountLabel = "50% OFF",
      imageUrl = "https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=1200&auto=format&fit=crop&q=80",
      promoCode = "SUPER50"
    )
  )

  val products = listOf(
    // Featured
    Product(
      id = "p_1",
      name = "AeroPods Pro 2026 Spatial Audio",
      category = ProductCategory.TECH,
      price = 189.99,
      originalPrice = 249.99,
      rating = 4.9,
      reviewCount = 1420,
      description = "Next-generation ultra-low latency wireless earbuds with biometric sensors, active noise cancellation 3.0, and 48-hour battery case.",
      specs = listOf("Bluetooth 5.4 LE Audio", "Active Noise Cancellation 3.0", "48h Total Battery", "IPX8 Waterproof"),
      tag = "BEST SELLER",
      imageUrl = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      isFeatured = true,
      isPopular = true,
      discountPercent = 24,
      stockLeft = 14,
      totalStock = 60,
      latitude = 0.3136,
      longitude = 32.5811,
      locationName = "Kampala Posta Main Depot, Kampala Rd",
      distanceKm = 0.8
    ),
    Product(
      id = "p_2",
      name = "Posta Kinetic Streetwear Hoodie",
      category = ProductCategory.FASHION,
      price = 79.50,
      originalPrice = 110.00,
      rating = 4.8,
      reviewCount = 530,
      description = "Heavyweight 450GSM organic cotton hoodie with electric violet reflective accents, oversized modern silhouette, and concealed kangaroo stash pocket.",
      specs = listOf("100% Organic French Terry", "Reflective Neon Piping", "Pre-shrunk Double Weave", "Relaxed Modern Fit"),
      tag = "TRENDING",
      imageUrl = "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
      isFeatured = true,
      isPopular = true,
      isNewArrival = true,
      discountPercent = 28,
      stockLeft = 9,
      totalStock = 40,
      latitude = 0.3340,
      longitude = 32.5880,
      locationName = "Kololo Fashion Hub, Prince Charles Dr",
      distanceKm = 2.4
    ),
    Product(
      id = "p_3",
      name = "Nova Pulse OLED Smart Watch 3",
      category = ProductCategory.TECH,
      price = 269.00,
      originalPrice = 329.00,
      rating = 4.9,
      reviewCount = 890,
      description = "Curved micro-OLED retina display with ECG monitoring, solar charging bezel, always-on AI assistant, and customizable tactile haptic crown.",
      specs = listOf("1.92\" Micro-OLED 120Hz", "Titanium Aerospace Case", "7-Day Battery Life", "5ATM Water Resistant"),
      tag = "HOT DEAL",
      imageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
      isFeatured = true,
      isSpecialOffer = true,
      discountPercent = 18,
      stockLeft = 18,
      totalStock = 50,
      latitude = 0.3315,
      longitude = 32.6050,
      locationName = "Nakawa Innovation Village Tech Lab",
      distanceKm = 3.9
    ),
    Product(
      id = "p_4",
      name = "CyberSneaker Zero Drift V2",
      category = ProductCategory.FASHION,
      price = 145.00,
      originalPrice = 195.00,
      rating = 4.7,
      reviewCount = 345,
      description = "Futuristic lifestyle sneaker featuring carbon-fiber responsive midsole plates, glowing electric violet outsole lugs, and breathable breathable mesh.",
      specs = listOf("Carbon Propulsion Plate", "Dual-density EVA foam", "Glow-in-the-dark Accents", "Ortholite Recycled Insole"),
      tag = "NEW DROP",
      imageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
      isFeatured = true,
      isNewArrival = true,
      discountPercent = 25,
      stockLeft = 6,
      totalStock = 30,
      latitude = 0.3160,
      longitude = 32.5760,
      locationName = "Nakasero Luxury Avenue, Lumumba Ave",
      distanceKm = 1.3
    ),

    // Popular
    Product(
      id = "p_5",
      name = "Lumina Aura Diffuser & Ambient Lamp",
      category = ProductCategory.HOME,
      price = 54.00,
      originalPrice = 75.00,
      rating = 4.6,
      reviewCount = 270,
      description = "Ultrasonic aroma diffuser with dynamic circadian lighting sync, silent magnetic mist motor, and smart home voice integration.",
      specs = listOf("500ml Reservoir", "16M RGB Dynamic Glow", "Ultra-quiet <20dB", "Schedule via Posta App"),
      tag = "POPULAR",
      imageUrl = "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80",
      isPopular = true,
      discountPercent = 28,
      stockLeft = 22,
      totalStock = 45,
      latitude = 0.3200,
      longitude = 32.6100,
      locationName = "Bugolobi Village Market & Lifestyle",
      distanceKm = 4.2
    ),
    Product(
      id = "p_6",
      name = "Vortex 4K Hologram Mini Projector",
      category = ProductCategory.TECH,
      price = 320.00,
      originalPrice = 420.00,
      rating = 4.9,
      reviewCount = 612,
      description = "Pocket-sized laser projector with automatic trapezoid correction, built-in Harman Kardon speakers, and 200-inch cinema projection.",
      specs = listOf("Native 4K HDR10+", "1500 ANSI Lumens", "Auto-Focus & Keystone", "3hr Battery Built-in"),
      tag = "TOP RATED",
      imageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
      isPopular = true,
      isSpecialOffer = true,
      discountPercent = 24,
      stockLeft = 8,
      totalStock = 35,
      latitude = 0.3470,
      longitude = 32.5920,
      locationName = "Ntinda Complex Tech Plaza, Kampala",
      distanceKm = 5.0
    ),
    Product(
      id = "p_7",
      name = "Glacier Glass Hydration Bottle 1L",
      category = ProductCategory.SPORTS,
      price = 34.99,
      originalPrice = 45.00,
      rating = 4.8,
      reviewCount = 415,
      description = "Triple-wall vacuum insulated stainless steel with UV-C auto-sanitizing cap, temperature display, and electric violet powder-coat finish.",
      specs = listOf("UV-C Sterilization Cap", "24h Cold / 12h Hot", "BPA-Free 316 Steel", "Leakproof Magnetic Cap"),
      tag = "ECO CHOICE",
      imageUrl = "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80",
      isPopular = true,
      isNewArrival = true,
      discountPercent = 22,
      stockLeft = 31,
      totalStock = 80,
      latitude = 0.3390,
      longitude = 32.5700,
      locationName = "Makerere Innovation Center, Kikoni",
      distanceKm = 2.9
    ),

    // New Arrivals
    Product(
      id = "p_8",
      name = "Prism Glow Peptide Serum 50ml",
      category = ProductCategory.BEAUTY,
      price = 48.00,
      originalPrice = 64.00,
      rating = 4.9,
      reviewCount = 189,
      description = "Bio-engineered triple peptide formula with hyaluronic spheres and blackberry extract for radiant skin barrier restoration.",
      specs = listOf("Triple Peptide 5%", "Niacinamide + HA", "Dermatologist Tested", "Cruelty-Free Vegan"),
      tag = "NEW ARRIVAL",
      imageUrl = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80",
      isNewArrival = true,
      discountPercent = 25,
      stockLeft = 19,
      totalStock = 60,
      latitude = 0.3080,
      longitude = 32.6180,
      locationName = "Muyenga Tank Hill Wellness Store",
      distanceKm = 5.6
    ),
    Product(
      id = "p_9",
      name = "Haptic Edge Wireless Mechanical Keyboard",
      category = ProductCategory.GAMING,
      price = 159.00,
      originalPrice = 199.00,
      rating = 4.8,
      reviewCount = 295,
      description = "Hot-swappable tactile switch keyboard with customizable OLED mini-display, RGB per-key underglow, and aluminum CNC chassis.",
      specs = listOf("75% Compact Layout", "Hot-Swap Gateron Switches", "Tri-Mode Wireless 2.4G", "OLED Custom Screen"),
      tag = "NEW ARRIVAL",
      imageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
      isNewArrival = true,
      discountPercent = 20,
      stockLeft = 11,
      totalStock = 40,
      latitude = 0.3550,
      longitude = 32.6010,
      locationName = "Kisasi Arcade Gaming Station",
      distanceKm = 6.2
    ),

    // Special Offers
    Product(
      id = "p_10",
      name = "OmniCharge 140W GaN Fast Charger",
      category = ProductCategory.ACCESSORIES,
      price = 49.99,
      originalPrice = 89.99,
      rating = 4.9,
      reviewCount = 820,
      description = "Ultra-compact Gallium Nitride power adapter with 3x USB-C PD 3.1 ports, intelligent power distribution, and travel pin adapters.",
      specs = listOf("140W Max Output", "3x USB-C + 1x USB-A", "GaN Infinity Tech", "Foldable Plug"),
      tag = "45% OFF FLASH",
      imageUrl = "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
      isSpecialOffer = true,
      discountPercent = 45,
      stockLeft = 5,
      totalStock = 70,
      latitude = 0.3150,
      longitude = 32.5850,
      locationName = "Posta Plaza Express Pickup, City Sq",
      distanceKm = 0.5
    ),
    Product(
      id = "p_11",
      name = "Apex Carbon Polarized Sunglasses",
      category = ProductCategory.ACCESSORIES,
      price = 62.00,
      originalPrice = 120.00,
      rating = 4.7,
      reviewCount = 310,
      description = "Aerospace titanium rimless frame with purple-tint UV400 mirror polarized lenses and anti-scratch hydrophobic coating.",
      specs = listOf("UV400 Polarized Lenses", "Ultralight 18g Frame", "Hydrophobic Coating", "Magnetic Leather Case"),
      tag = "50% OFF DEAL",
      imageUrl = "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80",
      isSpecialOffer = true,
      discountPercent = 48,
      stockLeft = 7,
      totalStock = 50,
      latitude = 0.3270,
      longitude = 32.5820,
      locationName = "Wandegeya High Street Boutique",
      distanceKm = 1.9
    )
  )

  val initialOrders = listOf(
    Order(
      id = "ord_101",
      orderNumber = "PM-2026-8841",
      date = "Sep 07, 2026",
      items = listOf(
        CartItem(product = products[0], quantity = 1, selectedColor = "Electric Violet", selectedSize = "Standard"),
        CartItem(product = products[4], quantity = 1, selectedColor = "Lavender Glow", selectedSize = "Standard")
      ),
      subtotal = 243.99,
      discount = 20.00,
      shipping = 0.00,
      total = 223.99,
      status = OrderStatus.IN_TRANSIT,
      trackingNumber = "PST-TRK-984210",
      estimatedArrival = "Tomorrow by 2:00 PM",
      deliveryAddress = "742 Evergreen Terrace, Suite 4B, Springfield"
    ),
    Order(
      id = "ord_102",
      orderNumber = "PM-2026-7294",
      date = "Aug 29, 2026",
      items = listOf(
        CartItem(product = products[1], quantity = 1, selectedColor = "Cosmic Black", selectedSize = "Large")
      ),
      subtotal = 79.50,
      discount = 10.00,
      shipping = 0.00,
      total = 69.50,
      status = OrderStatus.DELIVERED,
      trackingNumber = "PST-TRK-881920",
      estimatedArrival = "Delivered on Aug 31",
      deliveryAddress = "742 Evergreen Terrace, Suite 4B, Springfield"
    )
  )
}
